apiVersion: apps/v1
kind: Deployment
metadata:
  name: joke-maker
  namespace: sanalinker-dev
  labels:
    app: joke-maker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: joke-maker
  template:
    metadata:
      labels:
        app: joke-maker
    spec:
      containers:
      - name: joke-maker
        image: image-registry.openshift-image-registry.svc:5000/sanalinker-dev/joke-maker:latest
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: joke-maker
  namespace: sanalinker-dev
  labels:
    app: joke-maker
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: joke-maker
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: joke-maker
  namespace: sanalinker-dev
  labels:
    app: joke-maker
spec:
  to:
    kind: Service
    name: joke-maker
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
